### ISSUE TITLE
Resolving "java.lang.RuntimeException" (-212:Parsing error)

### ISSUE THREAD

**Issue by GiorgosXou** [cansik/deep-vision-processing#4]
# Solved
**if** you have this kind of issue:
```console
java.lang.RuntimeException: OpenCV(4.2.0) C:\projects\javacpp-presets\opencv\cppbuild\windows-x86_64\opencv-4.2.0\modules\dnn\src\darknet\darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: C:\Users\gxous\Desktop\χου\προγραμματισμός\java\TestDeepVision\TestDeepVision\lib\networks\yolov3.cfg in function 'cv::dnn::dnn4_v20191202::readNetFromDarknet'

        at org.bytedeco.opencv.global.opencv_dnn.readNetFromDarknet(Native Method)
        at ch.bildspur.vision.YOLONetwork.setup(YOLONetwork.java:42)
        at app.App.setup(App.java:29)
        at processing.core.PApplet.handleDraw(PApplet.java:2401)
        at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1557)
        at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
PS C:\Users\gxous\Desktop\χου\προγραμματισμός\java\TestDeepVision\TestDeepVision> 
```
**Then**, make sure that your project's directory doesn't have any non-latin characters like mines and your issue will be **solved.**
Also: [https://github.com/iArunava/YOLOv3-Object-Detection-with-OpenCV/issues/8](https://github.com/iArunava/YOLOv3-Object-Detection-with-OpenCV/issues/8)
<sub>*(if you want you can mark it as "good first issue")*<sub>

**Comment by cansik** [comment]
Thanks for pointing this out.

**Comment by RubensV94** [comment]
Thanks a lot, changing the name to some shorter solved my problem.
