### ISSUE TITLE
Nullpointer exception with Video Library and Processing 4

### ISSUE THREAD

**Issue by cansik** [cansik/deep-vision-processing#7]
Currently it's not possible to use processing 4 and the video library to inference webcam images. Here the stacktrace:

```processing
Processing video library using GStreamer 1.16.2
java.lang.NullPointerException
	at ch.bildspur.vision.util.CvProcessingUtils.toCv(CvProcessingUtils.java:104)
	at ch.bildspur.vision.network.BaseNeuralNetwork.convertToMat(BaseNeuralNetwork.java:28)
	at ch.bildspur.vision.network.BaseNeuralNetwork.run(BaseNeuralNetwork.java:18)
	at YOLOWebcamExample.draw(YOLOWebcamExample.java:71)
	at processing.core.PApplet.handleDraw(PApplet.java:2460)
	at processing.javafx.PSurfaceFX$1.handle(PSurfaceFX.java:91)
	at processing.javafx.PSurfaceFX$1.handle(PSurfaceFX.java:87)
	at com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(TimelineClipCore.java:239)
	at com.sun.scenario.animation.shared.TimelineClipCore.playTo(TimelineClipCore.java:197)
	at javafx.animation.Timeline.doPlayTo(Timeline.java:177)
	at javafx.animation.AnimationAccessorImpl.playTo(AnimationAccessorImpl.java:39)
	at com.sun.scenario.animation.shared.InfiniteClipEnvelope.timePulse(InfiniteClipEnvelope.java:110)
	at javafx.animation.Animation.doTimePulse(Animation.java:1101)
	at javafx.animation.Animation$1.lambda$timePulse$0(Animation.java:186)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.Animation$1.timePulse(Animation.java:185)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:344)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:515)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:499)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:492)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:320)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
NullPointerException
NullPointerException
WARNING: no real random source present!
```

**Comment by cansik** [comment]
The problem can be reproduced with the following example:

```processing
import processing.video.*;

import java.awt.image.*;
import java.nio.*;

Capture cam;

void setup() {
  size(640, 480);
  cam = new Capture(this, "pipeline:autovideosrc");
  cam.start();
}

void draw() {
  if (cam.available() == true) {
    cam.read();
  }

  image(cam, 0, 0, width, height);

  // expect NPE in Processing 4.0a3
  demo(cam);
}

void demo(PImage img) {
  BufferedImage image = (BufferedImage) img.getNative();
  WritableRaster raster = image.getRaster();
  DataBuffer dataBuffer = raster.getDataBuffer();
  DataBufferInt pixelBuffer = (DataBufferInt)dataBuffer;
  int[] pixels = pixelBuffer.getData();

  println("Pixels: " + pixels.length);
}
```

Related to https://github.com/processing/processing4/issues/80 (removal of AWT in PImage)

**Comment by cansik** [comment]
Fixed by using internal `PImage.pixels` directly. Please use `loadPixels()` if necessary (https://github.com/cansik/deep-vision-processing/commit/96065fb50a3d3a598c56839c1f06dd70b781f77c)
